version: "3.9"
services:
  dbtest:
    container_name: test_db
    image: postgres:9.6
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports: 
      - "5400:5432"

  web:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
